#!/bin/sh
rofi -show window -window-thumbnail -show-icons -font "Iosevka 10" -theme-str '#window {height: 94%; width:
95em; border: 0px 2px 0px 0px;}' -theme-str 'element-icon {size: 45%;}' -window-format '{w} {c} {t:20}' -columns 2
